export default interface IDatabaseArcSong {
  sid: string,
  name_en: string,
  name_jp: string,
  bpm: string,
  bpm_base: number,
  pakset: string,
  artist: string,
  time?: number,
  side: number,
  date: number,
  world_unlock: 'true' | 'false',
  remote_download: 'true' | 'false',
  rating_pst?: number,
  rating_prs?: number,
  rating_ftr?: number,
  rating_byn?: number,
  difficultly_pst: number,
  difficultly_prs: number,
  difficultly_ftr: number,
  difficultly_byn: number,
  notes_pst?: number,
  notes_prs?: number,
  notes_ftr?: number,
  notes_byn?: number,
  chart_designer_pst: string,
  chart_designer_prs: string,
  chart_designer_ftr: string,
  chart_designer_byn: string,
  jacket_designer_pst: string,
  jacket_designer_prs: string,
  jacket_designer_ftr: string,
  jacket_designer_byn: string
}
