// filename : __config__.js
// author   : CirnoBakaBOT
// date     : 04/09/2020
// comment  : api config

// const
const BOTARCAPI_MAJOR = 1;
const BOTARCAPI_MINOR = 0;
const BOTARCAPI_VERSION = 0;
const BOTARCAPI_VERSTR = `${BOTARCAPI_MAJOR}.${BOTARCAPI_MINOR}.${BOTARCAPI_VERSION}`;

// export const
module.exports =
{
  BOTARCAPI_MAJOR: BOTARCAPI_MAJOR,
  BOTARCAPI_MINOR: BOTARCAPI_MINOR,
  BOTARCAPI_VERSION: BOTARCAPI_VERSION,
  BOTARCAPI_VERSTR: BOTARCAPI_VERSTR
}