# This is a basic workflow to help you get started with Actions

name: NodeJS 14.x

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  node-14x:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repo
    - uses: actions/checkout@v2

    # NodeJS 14.x
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    # Initialize node modules
    - name: Initialize
      run: npm ci

    # Compile the project
    - name: Compile
      run: npm i -g typescript && tsc --build tsconfig.json

    # Test run
    - name: Test Run
      run: npm test
